packages:
  - 'examples/*'
  - 'packages/*'

allowBuilds:
  esbuild: true
  lightningcss: true
  sharp: true
  workerd: true
minimumReleaseAgeExclude:
  - '@tanstack/query-core@5.102.4'
  - '@tanstack/query-devtools@5.102.4'
  - '@tanstack/react-query-devtools@5.102.4'
  - '@tanstack/react-query@5.102.4'
