/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiMcpOauthClientRouteImport } from './routes/api.mcp-oauth-client'
import { Route as ApiMcpProxyRouteImport } from './routes/api.mcp-proxy'
import { Route as ApisApiIdPaneChar123OperationIdChar125RouteImport } from './routes/apis.$apiId.$pane.{-$operationId}'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMcpOauthClientRoute = ApiMcpOauthClientRouteImport.update({
  id: '/api/mcp-oauth-client',
  path: '/api/mcp-oauth-client',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMcpProxyRoute = ApiMcpProxyRouteImport.update({
  id: '/api/mcp-proxy',
  path: '/api/mcp-proxy',
  getParentRoute: () => rootRouteImport,
} as any)
const ApisApiIdPaneChar123OperationIdChar125Route =
  ApisApiIdPaneChar123OperationIdChar125RouteImport.update({
    id: '/apis/$apiId/$pane/{-$operationId}',
    path: '/apis/$apiId/$pane/{-$operationId}',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/api/mcp-oauth-client': typeof ApiMcpOauthClientRoute
  '/api/mcp-proxy': typeof ApiMcpProxyRoute
  '/apis/$apiId/$pane/{-$operationId}': typeof ApisApiIdPaneChar123OperationIdChar125Route
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api/mcp-oauth-client': typeof ApiMcpOauthClientRoute
  '/api/mcp-proxy': typeof ApiMcpProxyRoute
  '/apis/$apiId/$pane/{-$operationId}': typeof ApisApiIdPaneChar123OperationIdChar125Route
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/api/mcp-oauth-client': typeof ApiMcpOauthClientRoute
  '/api/mcp-proxy': typeof ApiMcpProxyRoute
  '/apis/$apiId/$pane/{-$operationId}': typeof ApisApiIdPaneChar123OperationIdChar125Route
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/api/mcp-oauth-client'
    | '/api/mcp-proxy'
    | '/apis/$apiId/$pane/{-$operationId}'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/api/mcp-oauth-client'
    | '/api/mcp-proxy'
    | '/apis/$apiId/$pane/{-$operationId}'
  id:
    | '__root__'
    | '/'
    | '/api/mcp-oauth-client'
    | '/api/mcp-proxy'
    | '/apis/$apiId/$pane/{-$operationId}'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApiMcpOauthClientRoute: typeof ApiMcpOauthClientRoute
  ApiMcpProxyRoute: typeof ApiMcpProxyRoute
  ApisApiIdPaneChar123OperationIdChar125Route: typeof ApisApiIdPaneChar123OperationIdChar125Route
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/mcp-oauth-client': {
      id: '/api/mcp-oauth-client'
      path: '/api/mcp-oauth-client'
      fullPath: '/api/mcp-oauth-client'
      preLoaderRoute: typeof ApiMcpOauthClientRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/mcp-proxy': {
      id: '/api/mcp-proxy'
      path: '/api/mcp-proxy'
      fullPath: '/api/mcp-proxy'
      preLoaderRoute: typeof ApiMcpProxyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/apis/$apiId/$pane/{-$operationId}': {
      id: '/apis/$apiId/$pane/{-$operationId}'
      path: '/apis/$apiId/$pane/{-$operationId}'
      fullPath: '/apis/$apiId/$pane/{-$operationId}'
      preLoaderRoute: typeof ApisApiIdPaneChar123OperationIdChar125RouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApiMcpOauthClientRoute: ApiMcpOauthClientRoute,
  ApiMcpProxyRoute: ApiMcpProxyRoute,
  ApisApiIdPaneChar123OperationIdChar125Route:
    ApisApiIdPaneChar123OperationIdChar125Route,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
